### ISSUE TITLE
Custom CSS Styling to ttty Terminal?

### ISSUE THREAD

**Issue by bcmckay** [mkrl/ttty#33]
Hi,

I am wondering how to actually implement custom CSS styling using the documentation you provided, having issues referencing it on our js page, and also not sure how to setup the CSS file. I created my own CSS page to override the custom variables you provided, but does not seem to work. 

If you could please provide an example on how this is done that would be great.

Thank you,
Brian

**Comment by mkrl** [comment]
My apologies, I've not been monotoring issues for this project for quite some time. I assume this is no longer relevant, but please reply to the issue if it is and I can come up with an up-to-date example.
