### ISSUE TITLE
Q: is it possible to initialize with items in the command history ?

### ISSUE THREAD

**Issue by dmccuskey** [mkrl/ttty#40]
i'm thinking about using this in a software prototype. wondering if i can initialize with items in command history so that user can simply use up-arrow to find previous commands thus won't have to type, avoiding mistakes / interrupting flow of testing.

thanks, dmc

ps, super cool project !

**Comment by mkrl** [comment]
Hey! This is actually something I wanted to implement a while ago, very simple change. It should be released in `1.5.0` in a couple of minutes.

**Comment by dmccuskey** [comment]
this is amazing ! thank you very much.
