### ISSUE TITLE
can I just embed this as a js file into an html page or do i have to spin up a server?

### ISSUE THREAD

**Issue by DangerDrome** [mkrl/ttty#43]
can I just embed this as a js file into an html page or do i have to spin up a server?

**Comment by mkrl** [comment]
My apologies, I've not been monotoring issues for this project for quite some time. I assume this is no longer relevant, but please reply to the issue if it is and I can help.

You can get embed the file as stated in the docs [here](https://github.com/mkrl/ttty?tab=readme-ov-file#in-a-browser-directly).
