### ISSUE TITLE
[Feature Request] Add option to disable scrollIntoView when printing

### ISSUE THREAD

**Issue by asanvicentec** [mkrl/ttty#44]
**Is your feature request related to a problem? Please describe.**
What I am currently trying to do is to render strings with line breaks in a for loop, also using **start()** and **stop()** methods, and for each iteration the page keeps scrolling automatically until I stop the command and break the loop.

**Describe the solution you'd like**
https://github.com/mkrl/ttty/blob/7570c9a0442200e0603a23f147bae1c64345a7f4/src/api/print.ts#L12C3-L12C25
Here I would like to pass a boolean to specify that I don't want to scroll and avoid applying **input.scrollIntoView()**, it could be an optional parameter and scroll by default like it does until now, or any other more elegant solution that solves this issue is fine.

Thanks for your work, I really like this project, it's really fancy :)

**Comment by mkrl** [comment]
Thank you! I'm surprised this package actually has some consumers :)
Just released in [1.7.0](https://github.com/mkrl/ttty/releases/tag/v1.7.0), you can check out the linked [PR](https://github.com/mkrl/ttty/pull/45) for details.

**Comment by asanvicentec** [comment]
Such a quick response lol, thank you so much!
